version: '3'

networks:
 private:
 web:
  external:
   name: web

services:
 #-------------
 #---Traefik---
 #-------------
 traefik:
  image: traefik:v2.4.2
  ports:
   - 80:80
   - 443:443
#   - 8080:8080
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock:ro
#   - $PWD/traefik.toml:/etc/traefik/traefik.toml
#   - $PWD/acme.json:/acme.json
   - /docker/letsencrypt:/letsencrypt
  networks:
   - web
  command:
   - --log.level=DEBUG
   - --api.insecure=true
   - --providers.docker=true
   - --providers.docker.exposedbydefault=true
   - --entrypoints.web.address=:80
   ####---- start decomment for prod -----  ####
   - --entrypoints.websecure.address=:443
   #- --entrypoints.web.http.redirections.entryPoint.to=websecure
   #- --entrypoints.web.http.redirections.entryPoint.scheme=https
   #- --certificatesresolvers.myresolver.acme.httpchallenge=true
   #- --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
   #- --certificatesresolvers.myresolver.acme.email=projetthiptop@gmail.com
   # - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
  ####---- end decomment for prod -----  ####

#   - --api.dashboard=true
#   - --api.insecure=true
#   - --entrypoints.web.address=:80
#   - --providers.docker=true
#   - --providers.docker.watch=true
#   - --providers.docker.network=web
#   - --providers.docker.exposedbydefault=false
#   - --log.level=debug
#   - --certificatesresolvers.mytlschallenge.acme.tlschallenge.entrypoint=websecure
  labels:
   - traefik.enable=true
   - traefik.http.routers.traefik.rule=Host(`traefik.${HOST_URL}`)
   - traefik.http.services.traefik.loadbalancer.server.port=8080
   - traefik.http.routers.traefik.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.traefik.tls=${TLS}
   - traefik.http.routers.traefik.tls.certresolver=myresolver
   - traefik.http.routers.traefik-https.tls=${TLS}
#   - traefik.http.routers.traefik-https.tls.domains[0].main=*.${HOST_URL}
#   - traefik.http.routers.traefik-https.tls.domains[0].sans= ${HOST_URL}
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"
  restart: always

 #----------
 #---Gogs---
 #----------
 gogs-db:
  image: postgres:13-alpine
  volumes:
   - ./data/gogs/postgres:/var/lib/postresql/data
  networks:
   - private
  environment:
   - POSTGRES_DB=gogs
   - POSTGRES_USER=gogs
   - POSTGRES_PASSWORD=gogs
  restart: always


 nexus:
  container_name: nexus
  image: sonatype/nexus3
  restart: always
  networks:
   - web
  volumes:
   - /nexus-data:/nexus-data 
  labels:
   - traefik.port=8081
   - traefik.http.routers.nexus.rule=Host(`nexus.${HOST_URL}`)
   - traefik.enable=true
   - traefik.http.routers.nexus.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.nexus.tls=${TLS}
   - traefik.http.routers.nexus.tls.certresolver=myresolver
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"

 gogs:
  image: gogs/gogs:0.12
  ports: 
   - 2222:2222
  volumes:
   - ./data/gogs/data:/data
  networks:
   - web 
  labels:
   - traefik.enable=true
   - traefik.http.routers.gogs.rule=Host(`gogs.${HOST_URL}`)
   - traefik.http.services.gogs.loadbalancer.server.port=3000
   - traefik.http.routers.gogs.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.gogs.tls=${TLS}
   - traefik.http.routers.gogs.tls.certresolver=myresolver
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"
  restart: always

 whoami:
  image: "traefik/whoami"
  container_name: "simple-service"
  labels:
   - traefik.enable=true
   - traefik.http.routers.whoami.rule=Host(`whoami.${HOST_URL}`)
   - traefik.http.routers.whoami.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.whoami.tls=${TLS}
   - traefik.http.routers.whoami.tls.certresolver=myresolver

 #-------------
 #---Jenkins---
 #-------------
 
 jenkins:
   build: images/jenkins
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data/jenkins:/var/jenkins_home
   networks:
    - web
   labels:
    - traefik.enable=true
    - traefik.http.routers.jenkins.rule=Host(`jenkins.${HOST_URL}`)
    - traefik.http.services.jenkins.loadbalancer.server.port=8080
    - traefik.http.routers.jenkins.entrypoints=${TRAEFIK_ENTRYPOINTS}
    - traefik.http.routers.jenkins.tls=${TLS}
    - traefik.http.routers.jenkins.tls.certresolver=myresolver
   extra_hosts:
    - "${HOST_URL}:${HOST_IP}"
    - "traefik.${HOST_URL}:${HOST_IP}"
    - "gogs.${HOST_URL}:${HOST_IP}"
    - "jenkins.${HOST_URL}:${HOST_IP}"
    - "nexus.${HOST_URL}:${HOST_IP}"
    - "whoami.${HOST_URL}:${HOST_IP}"
    - "cadvisor.${HOST_URL}:${HOST_IP}"
    - "prometheus.${HOST_URL}:${HOST_IP}"
    - "grafana.${HOST_URL}:${HOST_IP}"
   restart: always


 cadvisor:
  image: google/cadvisor
  container_name: cadvisor
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  networks:
   - web
  labels:
   - traefik.enable=true
   - traefik.http.routers.cadvisor.rule=Host(`cadvisor.${HOST_URL}`)
   - traefik.http.services.cadvisor.loadbalancer.server.port=8080
   - traefik.http.routers.cadvisor.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.cadvisor.tls=${TLS}
   - traefik.http.routers.cadvisor.tls.certresolver=myresolver
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"
  restart: always

 prometheus:
  image: prom/prometheus:latest
  container_name: prometheus
  volumes:
   - ./prometheus/:/etc/prometheus/
   - prometheus-data:/prometheus
  command:
   - '--config.file=/etc/prometheus/prometheus.yml'
   - '--storage.tsdb.path=/prometheus'
   - '--web.console.libraries=/etc/prometheus/console_libraries'
   - '--web.console.templates=/etc/prometheus/consoles'
   - '--storage.tsdb.retention=200h'
  networks:
   - web
  labels:
    - traefik.enable=true
    - traefik.http.routers.prometheus.rule=Host(`prometheus.${HOST_URL}`)
    - traefik.http.services.prometheus.loadbalancer.server.port=9090
    - traefik.http.routers.prometheus.entrypoints=${TRAEFIK_ENTRYPOINTS}
    - traefik.http.routers.prometheus.tls=${TLS}
    - traefik.http.routers.prometheus.tls.certresolver=myresolver
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"
  restart: always

 grafana:
  image: grafana/grafana:latest
  container_name: grafana
  volumes:
   - grafana-data:/var/lib/grafana
  networks:
   - web
  labels:
   - traefik.enable=true
   - traefik.http.routers.grafana.rule=Host(`grafana.${HOST_URL}`)
   - traefik.http.services.grafana.loadbalancer.server.port=3000
   - traefik.http.routers.grafana.entrypoints=${TRAEFIK_ENTRYPOINTS}
   - traefik.http.routers.grafana.tls=${TLS}
   - traefik.http.routers.grafana.tls.certresolver=myresolver
  extra_hosts:
   - "${HOST_URL}:${HOST_IP}"
   - "traefik.${HOST_URL}:${HOST_IP}"
   - "gogs.${HOST_URL}:${HOST_IP}"
   - "jenkins.${HOST_URL}:${HOST_IP}"
   - "nexus.${HOST_URL}:${HOST_IP}"
   - "whoami.${HOST_URL}:${HOST_IP}"
   - "cadvisor.${HOST_URL}:${HOST_IP}"
   - "prometheus.${HOST_URL}:${HOST_IP}"
   - "grafana.${HOST_URL}:${HOST_IP}"
  restart: always

volumes:
  prometheus-data: {}
  grafana-data: {}